const UICONSTANTS = {
  rankDropdownLabel: "Rank",
  modeOfCommunicationsDropdownLabel: "Mode",
  reportCategoryLabel: "Report Category",
  formTypeLabel: "Form Type",
  reportTypeLabel: "Report type",
  AppraisalCycleLabel:"Appraisal Cycle",
  lookUpTablenames: "LookUp Table Name",
  staffCategoryLabel: "Staff Category",
  gradeCategoryLabel: "Grade Category",
  batchIdLabel: "Batch ID",
  StaffName: "Staff Name",
  AppraiseeName:"Appraisee Name",
  ApprasialReportID: "Apprasial Report ID",
  ReportID: "Report ID",
  Name: "Name",
  Status: "Status",
  Department: "Department",
  Division: "Division",
  Branch: "Branch",
  Section: "Section",
  Issue: "Issued",
  reportIdLabel: "Report ID",
  staffNameLabel: "Staff Name ",
  departmentDropdown: "Department",
  divisionDropdown: "Division",
  branchDropdown: "Branch",
  sectionDropdown: "Section",
  reportStatusDropdown: "Report Status",
  bookMarksDropdown: "Bookmarks",
  menuitem_menu: "Menu",
  menuitem_signout: "Log out",
  clear: "Clear",
  overdue: "Report overdue",
  firstreminder: "1st Reminder Generated",
  secondreminder: "2nd Reminder Generated",
  daysoverdue: "Days Overdue(from Interview Officer Due Date)",
  analysisCycle:"Appraisal Cycle",
  senporforma:"Send Proforma to",
  responsible:"Responsible Officer",
  designation:"Designation",
  titles: {
    staffReportsBatch: "Search Staff Reports Batch",
    staffReportsBatch_Preview: "Preview batch details",
    staffReportsBatch_EditBatch: "Edit Batch",
    staffReportsBatch_addAppraisal: "Add Appraisal",
    staffReportsBatch_editAppraisal: "Edit Appraisal",
    staffAppraisalReport: "Staff Appraisal Reports",
    moderation: "Moderation",
    moderationDetail: "Moderation Detail",
    specialAppraisalReport: "C&SD SRS Version:1.00-Google Chrome",
    specialAppraisal_search: "Search Special Appraisals",
    specialAppraisal_Home:"Special Appraisal",
    bookInOut: "Book-in/out Reports",
    bookInOut_ViewBookingRecords: "My book-in/out Records",
    bookInOut_ViewAllBookingRecords:"Book-in/out Records",
    bookInOut_ViewAppraisalRecords: "Appraisal Report Booking Reocrds",
    PerformanceRatings: "Performance Ratings",
    trackAppraisalReport: "Track Appraisal Report",
    appealratings: "Appeal Ratings",
    lookUpTables: "Lookup tables",
    analysisReports:"Analysis Reports",
    GrantIncrementReport:"Grant Increment Report",
    DPAccountDeletionList:"DP Account Deletion List",
    OverallPerformance:"Overall Performance of Past 10 Years",
    PostingHistory:"Post Report",
    SeniorityRatinhReport:"Seniority Rating Report",
    DocumentTemplate:"Eform Templates",
    EmailTemplate:"Email Templates"
  },
  staffReportsBatch: {
    datetimePicker_fromDate: "Batch Issue Date (from)",
    datetimePicker_toDate: "Batch Issue Date (to)",
    button_createReportBatch: "Create Staff Reports Batch",
    button_removeReportBatch: "Remove Staff Reports Batch",
    button_saveReportBatch: "Save Special Appraisal",
    radiogroup_grade: "Grade Category",
    radiogroup_staff: "Staff Category",
    radiogroup_report: "Report Category",
    radiogroup_annual: "Annual Report sub-category",
    createbatch_batchIdTxt: "Batch ID",
    createbatch_batchIdDesc: "Batch ID will be generated",
    createbatch_issueDateTxt: "Batch Issue Date",
    createbatch_btnCreate: "Create",
    createbatch_btnCancel: "Cancel",
    batchDetails: {
      btnExport: "Export",
      btnPrint: "Print Covering Label",
      btnEditProforma: "Edit Proforma",
      btnIssueProforma: "Issue Proforma",
      btnEditOutpostMemo: "Edit Outpost Memo",
      btnIssueOutpostMemo: "Issue Outpost Memo",
      btnPreviewReport: "Preview Staff Report",
      btnIssueReport: "Issue Staff Report",
      btnAdd: "Add",
      btnRemove: "Remove",
      btnUpdateRemark: "Update Report Remark",
      btnUpdateEndDate: "Update Report End Date",
      btnUpdateReportType: "Update Report Type",
      btnIssueEmail: "Issue Email for Revision",
      btnCreate: "Create",
      btnCancel: "Cancel",
      txtBatchId: "Batch ID",
      txtBatchCreateDate: "Batch Created Date",
      txtProformaIssueDate: "Proforma Issue Date",
      txtMemoIssueDate: "Memo Issue Date",
      txtReportIssueDate: "Report Issue Date",
    },
    addOrEditAppraisal: {
      txtReportId: "Report ID",
      txtReportType: "Report Type",
      txtStaffName: "Staff Name",
      txtPresentSubstantiveRank: "Present Substantive Rank",
      txtStatus: "Status",
      txtDepartment: "Department",
      txtDivision: "Division",
      txtBranch: "Branch",
      txtSection: "Section",
      txtProposedIssueDate: "Proposed Issue Date",
      txtAppraiseeSignatureDate: "Appraisee Signature Date",
      txtIssueDate: "Issue Date",
      txtReportStart: "Report Start",
      txtReportEnd: "Report End",
      txtDateOfFirstAppointment: "Date of First Appointment",
      txtRankOfFirstAppointment: "Rank of First Appointment",
      txtDateOfAppointmentToPresent:
        "Date of appt. to Present Substantive Rank",
      txtTermOfAppointment: "Terms of Appointment",
      txtPresentPost: "Present post",
      txtDateToPresentPost: "Date to Present Post",
      txtSubstantiveSalaryPoint: "Substantive Salary Point",
      txtNextIncrementalDate: "Next Incremental Date",
      txtPersonnelRemarks: "Report Remarks",
      btnSave: "Save",
      btnCancel: "Cancel",
    },
    editProforma: {
      appraisalReportId: "Appraisal Report ID",
      from: "From",
      to: "To",
      ref: "Ref.()",
      in: "In",
      fromType: "From type",
      tel: "Tel.",
      status: "Status",
      fax: "Fax",
      email: "Email",
      date: "Date",
      staffId: "Reportee Staff ID",
      name: "Name of Reportee",
      rank: "Rank",
      nature: "Report Nature",
      remark: "Remark",
      periodFrom: "Report Period(from)",
      periodTo: "Report Period(to)",
      tips: "(This proforma should be attached to the staff report)",
      dptName: "Outpost Department Name",
      toEmail:"To Email",
      introduceText:"Introduce Text"
    },
    viewSatffProfile: {
      englishFullName: "Full Name of Officer(English)",
      ChineseFullName: "Full Name of Officer(Chinese)",
      birth: "Month and Year of Birth",
    },
  },
  staffAppraisalReport: {
    datetimePicker_startDate: "Report Start Date (from)",
    datetimePicker_endDate: "Report Start Date (to)",
    datetimePicker_issueFromDate: "Report Issue Date (from)",
    datetimePicker_issueEndDate: "Report Issue Date (to)",
    button_saveSearchCriteria: "Save Search Criteria",
    button_loadSearchCriteria: "Load Search Criteria",
    button_search: "Search",
    button_exportRating: "Export Rating",
    searchCriteria: "Search Criteria",
    general: "General",
    name: "Name",
    criterias: "Criteria",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    performanceRating: "Performance Rating ",
    close: "Close",
  },
  auditRecords: {
    datetimePicker_startDate: "Action Date (from)",
    datetimePicker_endDate: "Action Date (to)",
    adId: "AD ID",
    acessTime: "Access Time",
    module: "Module",
    action: "Action",
    actionDetail: "Action Details"
  },
  specialAppraisal: {
    createSpecial: "Add Special Appraisal",
    removeSpecial: "Remove Special Appraisal",
    specialRank: "Present substantive rank",
    appraisalTitle: "Staff Search",
    appraisalName: "Staff Name",
    rank: "Rank",
    department: "Department",
    division: "Division",
    branch: "Branch",
    section: "Section",
    result: "Results:",
  },
  performanceratings: {
    searchResult: "Search Results:",
    appraisalName: "Appraisee Name",
  },
  EformTemplate: {
    aoname: "AO Name",
    aopost: "AO Post/Rank",
    coname: "CO Name",
    copost: "CO Post/Rank",
  },
  personnelRemarksComponent: {
    label: "Report Remarks",
    btnAddRemarks: "Add Remarks",
    btnClear: "Clear",
    btnCopy: "Copy to Clipboard",
    dialogDate: "Effect at",
  },
  preloadDropdownLables: {
    reportRemarksType: "Report Remark Type",
    actingDropdown: "Acting",
    specialAppraisalReportStatus: "Status",
  },
  bookInOut: {
    scannerFieldLabel: "Appraisal Report ID",
  },
  moderationDetail:{
    moderationDetailId:"Moderation ID",
    moderationGeneral:"General",
    moderationName:"Moderation Name",
    moderationAssessment:"Assessment Panel?Rank",
    moderationAppraisalReports:"Appraisal Reports",
    updateOfCommunicatioin:"Mode of Communication",
    moderationDetailComments:'Moderation: M210002 for SS',
    moderationAddAppraisal:"Add Appraisal Report(s)",
    button_Delete:"Clear",
    moderationMoveAnother:"Move Reports to Another Moderation Session",
    moderationSendToMember:"Invite for Members' Comments",
    moderationCopyLink:"Link for HoG",
    consolidateChairperson:"Comment Deadline for Chairperson"
  },
  trackAppraisalReport: {
    updateremark: "Update Report Remarks",
    firstGenerate: "Generate 1st Outstanding Reminder",
    secondGenerate: "Generate 2nd Outstanding Reminder",
  },
  userAdministration:{
    name:"User Name",
    loginId:"AD ID",
    govhrmsEmail:"GovHRMS Email Address",
    preferEmail:"Prefer Email Address",
  },
  lookUp:{
    key:"Code",
    description:"Description",
    order:"Order"
  },
  lookUpTable:{
    addReferenceCategroy:"Add Reference Categroy"
  },
  role:{
    name:"Role Name",
    isSystemReserved:"Is System Reserved",
    isBoardRole:"Is Board Role",
    allowSpecifyRank:"Allow Specify Rank",
  },
  staff:{
    englishName:"Full Name of Office(English)",
    chineseName:"Full Name of Office(Chinese)",
    birth:"Month and year of birth",
  },
  emailAccount:{
    serverAddress:"Server Address",
    description:"Description",
    userName:"User Name",
    password:"Password",
    mailFile:"Mail File",
    portNumber:"Port Number",
    serverType:"Server Type",
    emailContainRank:"Key",
    emailAccountId:"Email Account",
  },
  nopermissionToolTip: "You do not have permission to access this function.",
  noEditToolTip: "Can not save: This Special report has been associated with an Appraisal report.",
  noEmailSaveToolTip: "Can not save: This Email Template has been associated with an Email Template.",
  profotma:{
    postTile:"From Officer Post Title",
    fileRef:"File Reference",
    order:"order",
    dayCount:"Day Count",
    returnTo:"Return Proforma to"
  },
  outpostMemo:{
    postTile:"From Officer Post Title",
    fromOfficeName:"From Officer Name",
    telNo:"Officer Tel No",
    faxNo:"Officer Fax No",
    refNo:"Reference No",
    refIn:"Reference In",
    introduceText1:"Introduce Text1",
    introduceText2:"Introduce Text2",
  },
  outpostFunctional:{
    deptCode:"Department Code",
    divisionCode:"Division Code",
    branchCode:"Branch Code",
    sectionCode:"Section Code",
    functional:"Function Supervisor"
  },
  emailTemplate:{
    templateType:"Template Type",
    isOutPost:"Is Outpost",
    rankAbbr:"Rank Abbr",
    description:"Description"
  }
};

export default UICONSTANTS;
